name: "My action"
description: "Test my action"

inputs:
  message:
    description: "el mensaje a imprimir"
    required: true
    default: "hi"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "Hola ${{  inputs.message  }}"
      shell: bash